
   <div id="privacy-container">
        <div id="content" class="row">
            <div id="privacy" class="col-md-10">
                <header class="page-header">
                    <h2>
                        Legal Disclosure        </h2>
                </header>
                <article class="text-justify">
                    <p>
                        Information in accordance with section 5 TMG
                    </p>
                    <p>
                        University of Kassel<br/>
                        Henschelstraße 4<br/>
                        34127 Kassel<br/>
                        Germany <br/>
                    </p>


                    <h3>Represented by</h3>
                    <p>
                        Ali Sunyaev<br/>
                        Henschelstraße 4<br/>
                        34127 Kassel <br/>
                        Germany<br/>
                    </p>

                    <h3>Contact</h3>
                    <p>
                        Telephone: +49 561 804-7924<br/>
                        Telefax: +49 561 804-3621<br/>
                        Email: <a href="mailto:webmaster@uni-kassel.de" class="black">webmaster@uni-kassel.de</a><br/>
                    </p>

                    <h3>Person responsible for content in accordance with 55 Abs. 2 RStV</h3>
                    <p>
                        Ali Sunyaev<br/>
                        Henschelstraße 4<br/>
                        34127 Kassel <br/>
                        Germany<br/>
                    </p>
                    <p>
                        Telephone: +49 561 804-7924<br/>
                        Telefax: +49 561 804-3621<br/>
                        Email: <a href="mailto:webmaster@uni-kassel.de" class="black">webmaster@uni-kassel.de</a><br/>
                        Website: <a href="http://www.uni-kassel.de/fb07/institute/ibwl/personen-fachgebiete/sunyaev-prof-dr/home.html" class="black">www.uni-kassel.de</a>
                    </p>

                    <h3>VAT number</h3>
                    <p>
                        VAT indentification number in accorance with section 27 a of the German VAT act<br/>
                        DE 123486767
                    </p>

                    <h3>Disclaimer</h3>
                    <p>
                       <h4> Accountability for content</h4>
                        The contents of our pages have been created with the utmost care. However, we cannot guarantee the contents' accuracy, completeness or topicality. According to statutory provisions, we are furthermore responsible for our own content on these web pages. In this context, please note that we are accordingly not obliged to monitor merely the transmitted or saved information of third parties, or investigate circumstances pointing to illegal activity. Our obligations to remove or block the use of information under generally applicable laws remain unaffected by this as per §§ 8 to 10 of the Telemedia Act (TMG).
                    </p>
                    <p>
                        <h4>Accountability for links</h4>
                        Responsibility for the content of external links (to web pages of third parties) lies solely with the operators of the linked pages. No violations were evident to us at the time of linking. Should any legal infringement become known to us, we will remove the respective link immediately.
                    </p>
                    <p>
                        <h4>Copyright</h4>
                        Our web pages and their contents are subject to German copyright law. Unless expressly permitted by law (§ 44a et seq. of the copyright law), every form of utilizing, reproducing or processing works subject to copyright protection on our web pages requires the prior consent of the respective owner of the rights. Individual reproductions of a work are allowed only for private use, so must not serve either directly or indirectly for earnings. Unauthorized utilization of copyrighted works is punishable (§ 106 of the copyright law).
                    </p>
                </article><br/><br/><br/>
            </div>
        </div>
    </div>



