<?php use Phalcon\Tag as Tag; ?>

<div id="image"></div>

<div id="load">
    <div id="loading"></div>
    <div id="loading-text" style="margin-top: 28%;text-align: center; font-size: 20px;margin-left: 1%">Loading...</div>
</div>
<div  style="position:relative;" class="home-content">
	<div class="content" style="color:white;">
        <div>
        <?php
        	echo Phalcon\Tag::imageInput(array("src" => "/privacyplatform/img/logox.png" , "class" => "w3-circle logo"));
        ?>
        </div>
    	<div style="position:relative;font-size: 40px;margin-top: 2%;line-height: 30px" class="w3-text-shadow"><b><?php echo $t["Welcome to Privacy Platform"] ?></b></div>

        <p class = "w3-text-shadow" style="font-size: 21px;position: relative;margin-top: 2%"><?php echo $t["The platforms here are provided with the intentions for research purpose only. The data collected here from the users will never be used for commercial purposes.  </br>Feel free to use them."] ?></p>
        <br>
		<div style="position:relative;margin-top: 2%"><?php echo Tag::linkTo(array('about/index', $t['Learn more'], 'class' => 'btn btn-primary btn-large btn-default')) ?></div>
	</div>
    <div>
    </div>
</div>

