<?php use Phalcon\Tag as Tag; ?>
<?php echo Tag::form(array("privacypersonalitytest/next")) ?>
	  
<div class="ex2">
	<?php

         foreach($questions as $question){ ?>	
	<label  id="label_24" for="input_24"><br>
	<font color="red" size="4">	   	
	    <?php echo 'Question '. $question->id." : ";?>
	</font>
	<font  size="2">
            <?php echo "   Es ist mir wichtig, ".$question->questions. '  </br>';?>
	</font>
	</br></label>
	<table cellpadding="5" cellspacing="0" style="color:#808080;" >
            <tr class="ex3" >
              <th >
                &nbsp;
              </th>
              <th align="center">
                <label for="input_1"> 1 </label>
              </th>
              <th align="center">
                <label for="input_2"> 2 </label>
              </th>
              <th align="center">
                <label for="input_3"> 3 </label>
              </th>
              <th align="center">
                <label for="input_4"> 4 </label>
              </th>
              <th align="center">
                <label for="input_5"> 5 </label>
              </th>
              <th align="center">
                <label for="input_6"> 6 </label>
              </th>
              <th align="center">
                <label for="input_7"> 7 </label>
              </th>
              <th>
                &nbsp;
              </th>
            </tr>
            <tr>
              <td>
                <label for="input_1" style="font-size:15.2px"> Strongly<br />disagree </label>
              </td>
              <td align="center">
                <input  type="radio"  name="<?php echo $group?>" value="1" title="1" id="input_1" />
              </td>
              <td align="center">
                <input type="radio"  name="<?php echo $group?>" value="2" title="2" id="input_2" />
              </td>
              <td align="center">
                <input type="radio" name="<?php echo $group?>"  value="3" title="3" id="input_3" />
              </td>
              <td align="center">
                <input type="radio"  name="<?php echo $group?>" value="4" title="4" id="input_4" />
              </td>
              <td align="center">
                <input  type="radio" name="<?php echo $group?>" value="5" title="5" id="input_5" />
              </td>
              <td align="center">
                <input  type="radio"  name="<?php echo $group?>" value="6" title="6" id="input_6" />
              </td>
              <td align="center">
                <input type="radio"  name="<?php echo $group?>" value="7" title="7" id="input_7" />
              </td>
              <td>
                <label for="input_7" style="font-size:15.2px">    Strongly <br />agree  </label>
              </td>
            </tr>
          </table>
           <br></br></br></br>
           
	<?php $group = 'answer2';}?>
	
	<div class="ex4">
		<button onclick="goBack()" id="input_2" type="submit" class="buttonback">Back</button>
    	 	<button id="input_2" type="submit" class="buttonnext">Next</button>
	</div> 
 </div>
      </form>


